# Generated by Django 5.2.2 on 2025-06-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
