# Generated by Django 5.2.2 on 2025-06-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_events_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image',
        ),
    ]
