# Generated by Django 5.2.2 on 2025-06-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='for_class',
            field=models.IntegerField(null=True),
        ),
    ]
