# Generated by Django 5.2.2 on 2025-06-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_events_for_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
