# Generated by Django 5.2.2 on 2025-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_events_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Student_Data/')),
            ],
        ),
    ]
