# Generated by Django 5.2.2 on 2025-06-16 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_student_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='name',
            new_name='student_name',
        ),
        migrations.RemoveField(
            model_name='student_data',
            name='password',
        ),
        migrations.AddField(
            model_name='student_data',
            name='classs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student_data',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
