# Generated by Django 5.2.2 on 2025-06-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_rename_name_student_data_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.CharField(default='TBD', max_length=30),
        ),
    ]
