# Generated by Django 5.2.2 on 2025-06-23 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_events_time_events_venue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_data',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='image',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
        migrations.AddField(
            model_name='events',
            name='Money',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='Type',
            field=models.CharField(default='Program', max_length=30, verbose_name='Event Type'),
        ),
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='events',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event',
            field=models.CharField(max_length=100, verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='events',
            name='for_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(default='TBD', max_length=100),
        ),
    ]
