# Generated by Django 5.2.2 on 2025-06-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_delete_student_data_rename_date_events_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='Type',
            new_name='type',
        ),
    ]
