# Generated by Django 5.2.2 on 2025-06-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_rename_type_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='for_class',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
