# Generated by Django 5.2.2 on 2025-06-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Username',
            new_name='fullname',
        ),
    ]
