# Generated by Django 5.2.2 on 2025-06-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_rename_username_student_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
