# Generated by Django 5.2.2 on 2025-06-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_student_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='number',
            new_name='available',
        ),
    ]
