# Generated by Django 5.2.2 on 2025-07-15 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_rename_number_events_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='Money',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classess',
        ),
        migrations.RemoveField(
            model_name='student',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fullname',
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Kathmandu', max_length=60),
        ),
        migrations.AddField(
            model_name='student',
            name='class_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(default='Kathmandu', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Unnamed', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(default='Bagmati', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='street',
            field=models.CharField(default='Unknown Street', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='for_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='changeme123', max_length=70),
        ),
        migrations.AddField(
            model_name='events',
            name='money',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cost (if any)'),
        ),
    ]
