# Generated by Django 5.2.2 on 2025-07-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_remove_events_money_remove_student_classess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
