# Generated by Django 5.2.2 on 2025-07-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_alter_events_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='money',
            new_name='Money',
        ),
    ]
